### ISSUE TITLE
Repositorio Git

### ISSUE THREAD

**Issue by dpoeira91** [isel-leic-pdm/1415-2-LI61N#2]
Boa noite Engenheiro,

Pertenço ao grupo 11 da sua turma de PDM e tenho o utilizador Github associado a minha conta do thoth ou pelo menos ela aparece na minha página de perfil, no entanto,ainda não recebi acesso a um repositório git.

Resto de bom fim de semana,
Diogo Poeira

**Comment by jtrindade** [comment]
Aqui aparece a indicação de convite enviado.
Cancelei-a e enviei de novo.
A mensagem vai para a conta de email com que se registou no GitHub.

**Comment by dpoeira91** [comment]
Esqueça eu pensei que aparecia na página principal o repositório novo automáticamente.
Está resolvido, obrigado :+1:
